name: Sync Notion to Google Tasks

on:
  schedule:
    - cron: '0 8,12,16,20 * * *'

jobs:
  sync-notion:
    name: Sync Notion to Google Tasks
    runs-on: self-hosted

    steps:
      - name: Environment Setup
        run: |
          echo "Setting up environment on self-hosted runner..."

          # Prepare workspace — remove it if it exists, then recreate
          if [ -d "$HOME/github-workspace" ]; then
            echo "Directory $HOME/github-workspace already exists. Removing it..."
            rm -rf "$HOME/github-workspace"
          fi
          mkdir -p "$HOME/github-workspace"
          export GITHUB_WORKSPACE="$HOME/github-workspace"
          
          # Clone repository
          echo "Cloning repository..."
          git clone --branch main "https://github.com/${{ github.repository }}" "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"

          # Check if Poetry is already installed
          if ! command -v poetry &> /dev/null
          then
            echo "Poetry not found. Installing..."
            curl -sSL https://install.python-poetry.org | python3 -
          else
            echo "Poetry is already installed."
          fi
          export PATH="$HOME/.local/bin:$PATH"

          # Install dependencies
          poetry install
        env:
          PYTHON_VERSION: 3.10

      - name: Validate Dependencies
        run: |
          echo "Validating dependencies..."
          python3 --version
          poetry --version
          poetry check

      - name: Run Unit Tests
        run: |
          echo "Running tests..."
          poetry run pytest tests/unit --maxfail=1 --disable-warnings

      - name: Generate Google API Token
        run: |
          echo "Generating token file..."
          poetry run python3 "$GITHUB_WORKSPACE/services/google_task/config/config_creds.py" --save_dir "$GITHUB_WORKSPACE"
        env:
          GOOGLE_ACCESS_TOKEN: ${{ secrets.GOOGLE_ACCESS_TOKEN }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          PROJECT_ROOT: ${{ github.workspace }}

      - name: Sync Notion to Google Tasks
        run: |
          echo "Running sync script..."
          export TOKEN_PATH="${{ github.workspace }}/token.json"
          poetry run python3 "$GITHUB_WORKSPACE/main.py"
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          PROJECT_ROOT: ${{ github.workspace }}
