name: Sync Notion to Google Tasks

on:
  schedule:
    - cron: '0 8,12,16,20 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-notion:
    name: Sync Notion to Google Tasks
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python 3.10 if not installed
        run: |
          if ! command -v python3.10 &>/dev/null; then
            echo "Python 3.10 is not installed. Installing..."
            sudo apt-get update
            sudo apt-get install -y python3.10 python3.10-venv
          else
            echo "Python 3.10 is already installed."
          fi

      - name: Install Poetry if not installed
        shell: bash
        run: |
          if ! command -v poetry &>/dev/null; then
            echo "Poetry not found. Installing..."
            # Install Poetry using Python 3.10
            curl -sSL https://install.python-poetry.org | python3.10 -
            # Make sure Poetry is on the PATH for subsequent steps
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          else
            echo "Poetry is already installed."
          fi

      - name: Validate Dependencies
        run: |
          python3.10 --version
          poetry --version
          poetry check
        working-directory: ${{ github.workspace }}
        env:
          # We ensure our updated path from above is included
          PATH: $HOME/.local/bin:$PATH

      - name: Install Dependencies
        run: |
          poetry install
        working-directory: ${{ github.workspace }}
        env:
          PATH: $HOME/.local/bin:$PATH

      - name: Run Unit Tests
        run: |
          poetry run pytest tests/unit --maxfail=1 --disable-warnings
        working-directory: ${{ github.workspace }}
        env:
          PATH: $HOME/.local/bin:$PATH

      - name: Generate Google API Token
        run: |
          poetry run python3.10 services/google_task/config/config_creds.py --save_dir .
        working-directory: ${{ github.workspace }}
        env:
          GOOGLE_ACCESS_TOKEN: ${{ secrets.GOOGLE_ACCESS_TOKEN }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Sync Notion to Google Tasks
        run: |
          poetry run python3.10 main.py
        working-directory: ${{ github.workspace }}
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
